In [1]:
%load_ext autoreload
%autoreload 2
import utils as ut

In [3]:
from keras.backend.tensorflow_backend import set_session
from keras import optimizers
import tensorflow as tf
import json, os, argparse, imp
from keras.models import model_from_json

# model = model_check((250,117))
# model.summary()

In [55]:
modelPath = "./models/"
modelName = "RNN_a1"
with open(os.path.join(modelPath, modelName+'.json'), 'r') as f:
    model = model_from_json(f.read())

In [50]:
model_check.load_weights(os.path.join(modelPath, modelName+'1.wgt'))


AttributeError: 'function' object has no attribute 'load_weights'

In [24]:
weights_list = model.get_weights()

In [25]:
for i, weights in enumerate(weights_list[0:9]):
    print(i,weights.shape)

0 (117, 200)
1 (50, 200)
2 (200,)
3 (50, 26)
4 (26,)


In [56]:
model.layers[1]

In [36]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers.core import Dense, Dropout, Activation, Flatten, Reshape

def model_check(input_shape):
#     inp = Input(input_shape)
    model = Sequential()
    model.add(LSTM(50,input_shape = input_shape))
    model.add(Dense(26))
    model.add(Activation('softmax'))
    
#     encoded_l = model(inp)
    
    return model

In [37]:
mod_check = model_check((250,117))

In [38]:
for i, weights in enumerate(weights_list):
    model.layers[i]

NameError: name 'weights_list' is not defined

In [39]:
import keras
inputs = keras.Input((32,))
outputs = keras.layers.Dense(1)(inputs)
model = keras.Model(inputs, outputs)

In [40]:
import keras

In [41]:
inputs = keras.Input(shape=(784,), name="digits")
x = keras.layers.Dense(64, activation="relu", name="dense_1")(inputs)
x = keras.layers.Dense(64, activation="relu", name="dense_2")(x)
outputs = keras.layers.Dense(10, name="predictions")(x)
functional_model = keras.Model(inputs=inputs, outputs=outputs, name="3_layer_mlp")

# Extract a portion of the functional model defined in the Setup section.
# The following lines produce a new model that excludes the final output
# layer of the functional model.
pretrained = keras.Model(
    functional_model.inputs, functional_model.layers[-1].input, name="pretrained_model"
)



# Randomly assign "trained" weights.
for w in pretrained.weights:
    w.assign(tf.random.normal(w.shape))
pretrained.save_weights("pretrained_ckpt")
pretrained.summary()



Model: "pretrained_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
digits (InputLayer)          (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
Total params: 54,400
Trainable params: 54,400
Non-trainable params: 0
_________________________________________________________________


In [42]:
inputs = keras.Input(shape=(784,), name="digits")
x = keras.layers.Dense(64, activation="relu", name="dense_1")(inputs)
x = keras.layers.Dense(64, activation="relu", name="dense_2")(x)
outputs = keras.layers.Dense(10, name="predictions")(x)
functional_model = keras.Model(inputs=inputs, outputs=outputs, name="3_layer_mlp")

# Extract a portion of the functional model defined in the Setup section.
# The following lines produce a new model that excludes the final output
# layer of the functional model.
pretrained_2 = keras.Model(
    functional_model.inputs, functional_model.layers[-1].input, name="pretrained_model")

In [43]:
import tensorflow as tf
for i in range(len(pretrained.layers)):
    pretrained_2.layers[i].set_weights(pretrained.layers[i].get_weights())

In [44]:
pretrained_2.layers[1].set_weights(pretrained.layers[1].get_weights())

Making random weights for now. This will not be needed later

In [46]:
inputs = keras.Input(shape=(784,), name="digits")
x = keras.layers.Dense(64, activation="relu", name="dense_1")(inputs)
x = keras.layers.Dense(64, activation="relu", name="dense_2")(x)
outputs = keras.layers.Dense(10, name="predictions")(x)
functional_model = keras.Model(inputs=inputs, outputs=outputs, name="3_layer_mlp")

# Extract a portion of the functional model defined in the Setup section.
# The following lines produce a new model that excludes the final output
# layer of the functional model.
pretrained = keras.Model(
    functional_model.inputs, functional_model.layers[-1].input, name="pretrained_model"
)



# Randomly assign "trained" weights.
for w in pretrained.weights:
    w.assign(tf.random.normal(w.shape))
pretrained.save_weights("pretrained_ckpt")
pretrained.summary()

Model: "pretrained_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
digits (InputLayer)          (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
Total params: 54,400
Trainable params: 54,400
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# Forming loading model pipeline

In [47]:
def get_model():
    inputs = keras.Input(shape=(784,), name="digits")
    x = keras.layers.Dense(64, activation="relu", name="dense_1")(inputs)
    x = keras.layers.Dense(64, activation="relu", name="dense_2")(x)
    outputs = keras.layers.Dense(10, name="predictions")(x)
    functional_model = keras.Model(inputs=inputs, outputs=outputs, name="3_layer_mlp")
    return functional_model

In [50]:
source_model = get_model()
for w in source_model.weights:
    w.assign(tf.random.normal(w.shape))

In [65]:
for i in range(1,len(source_model.layers)):
    w = source_model.layers[i].weights  
    print(w[0].shape)

(784, 64)
(64, 64)
(64, 10)


In [62]:
source_model.summary()

Model: "3_layer_mlp"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
digits (InputLayer)          (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
predictions (Dense)          (None, 10)                650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________


In [73]:
input_Example = np.random.random((1,784))
pretrained.predict(input_Example)

(1, 64)

# Cross Domain sample-wise relevance

Cosine Similarity

In [4]:
import numpy as np
import pickle

In [18]:
num_features = 2
samples_trg = 3
samples_src = 4
features_src = np.random.random((samples_src,num_features))
features_trg = np.random.random((samples_trg,num_features))

In [19]:
total_Activities = 33
pickle_out = open('source_activities.pkl',"rb")
# src_act_array = pickle.load(pickle_out)
# trg_act_array = np.arange(total_Activities)[~np.isin(np.arange(total_Activities),src_act_array)]
src_act_array = np.arange(0,5)
trg_act_array = np.arange(5,8)
labels_src = np.random.choice(src_act_array, size=samples_src, replace=True, p=None)
labels_trg_supp = np.random.choice(trg_act_array, size=samples_trg, replace=True, p=None)

In [20]:
src_act_array,trg_act_array

(array([0, 1, 2, 3, 4]), array([5, 6, 7]))

In [21]:
labels_src,labels_trg_supp

(array([4, 0, 3, 1]), array([6, 5, 7]))

In [22]:
f_src_tilda = features_src/(np.linalg.norm(features_src,2,axis = 1))[:,None]
f_trg_tilda = features_trg/(np.linalg.norm(features_trg,2,axis = 1))[:,None]


sample-wise

In [23]:
A = np.zeros((samples_src,samples_trg))
for i in range(samples_src):
    for j in range(samples_trg):
        A[i,j] = np.exp(np.dot(f_src_tilda[i,:],f_trg_tilda[j,:]))

Class-wise

In [25]:
Classwise_weights = ut.classwise_weights(src_act_array,trg_act_array,labels_src,labels_trg_supp,A)

In [31]:
W = ut.soft_normalization(Classwise_weights)
W.shape

(5, 3)

In [32]:
ut.hard_normalization(Classwise_weights)

array([[0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])